services:
  - type: web
    name: pocket-option-telegram-bot
    env: python
    runtime: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      # OPTIONAL: set this if PO blocks Render IPs
      # - key: PO_PROXY_URL
      #   value: https://USER:PASS@proxy-host:port