services:
  - type: worker
    name: pocketoption-bot
    env: python
    plan: free
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TWELVE_API_KEY
        sync: false