services:
  - type: web
    name: pocket-option-telegram-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9